server:
  port: 8084
spring:
  application:
    name: transaction-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/transaction_db
  config:
    import: optional:configserver:http://localhost:8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka