package com.tnf.account_service.Dto.Request;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

import com.tnf.account_service.Enum.AccountType;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Schema(
        name = "CreateAccountRequest",
        description = "Payload to open a new account. The account number is generated by the service "
                + "and the balance always starts at 0, so neither is supplied here.")
public class CreateAccountRequest {

    @NotBlank(message = "customerId is required")
    @Schema(
            description = "Identifier of the customer who will own the account. Must reference an existing "
                    + "customer in the Customer Service; validated before the account is created.",
            example = "CUST1001",
            requiredMode = Schema.RequiredMode.REQUIRED)
    private String customerId;

    @NotNull(message = "accountType is required")
    @Schema(
            description = "Type of account to open.",
            example = "SAVINGS",
            requiredMode = Schema.RequiredMode.REQUIRED)
    private AccountType accountType;
}
